/**
 * Port the locked design system out of type-specimens/ into the extension.
 *
 * The specimen is the source of truth for type, colour, and icons (locked at
 * v2.2). Nothing under src/popup/popup.css, src/prep/prep.css,
 * src/pass/pass.css, or src/popup/glyphs.ts should be hand-edited — change the
 * specimen, run a desk crit, then re-run this:
 *
 *   npm run port:design
 *
 * Extension-only chrome (the popup window box, The Pass list, the Prep form)
 * has no specimen equivalent and is authored here, clearly separated.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ext = resolve(here, "..");
const specimens = resolve(ext, "../type-specimens");

const html = readFileSync(`${specimens}/popup-states.html`, "utf8");
const lines = html.split("\n");

// ── 1. Locate the port boundaries by content, not by hard-coded line numbers,
//       so an edit to the specimen shifts them safely.
const lineOf = (needle, from = 0) => {
  const i = lines.findIndex((l, n) => n >= from && l.includes(needle));
  if (i === -1) throw new Error(`port boundary not found: ${needle}`);
  return i;
};

const FONTS_START = lineOf("══════ Fonts ══════");
const TOKENS_END = lineOf("* { box-sizing: border-box; }", FONTS_START);
const POPUP_START = lineOf("─── Popup surface (shared)", TOKENS_END);
const POPUP_END = lineOf("─── Status legend", POPUP_START);

const dedent = (text) =>
  text
    .split("\n")
    .map((l) => (l.startsWith("      ") ? l.slice(6) : l))
    .join("\n")
    .replaceAll('url("./fonts/', 'url("../fonts/')
    .trimEnd();

/** @font-face blocks + the :root token block. Shared by all three surfaces. */
const tokens = dedent(lines.slice(FONTS_START, TOKENS_END).join("\n"));
/** Every `.popup ...` rule: card, skeleton, filmstrip, stamps, action row. */
const popupRules = dedent(lines.slice(POPUP_START, POPUP_END).join("\n"));

const banner = (surface, note) => `/* ══════════════════════════════════════════════════════════════
   Mise — ${surface}

   GENERATED by extension/scripts/port-design.mjs from
   type-specimens/popup-states.html. Do not hand-edit: change the
   specimen, run a desk crit, then \`npm run port:design\`.
   ${note}
   ══════════════════════════════════════════════════════════════ */
`;

// ── 2. popup.css ─────────────────────────────────────────────────
const popupWindow = `
/* ─── Popup window (extension-only; the specimen had no window) ── */

html,
body {
  width: 400px;
  margin: 0;
  padding: 0;
  background: var(--bg-page);
  color: var(--paper-primary);
  font-family: var(--font-body);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body {
  /* MV3 caps popup height at 600px. The card scrolls; the actions are pinned. */
  max-height: 600px;
  display: flex;
  flex-direction: column;
}

* { box-sizing: border-box; }

/* The specimen framed each card as a gallery tile; here the card IS the
   window, so it loses its border, shadow, and fixed width. */
.popup {
  width: 100%;
  border: 0;
  box-shadow: none;
  overflow-y: auto;
  flex: 1 1 auto;
}

/* .fired-stamp is inset:0 against .popup. While .popup scrolls, that box is
   the full content height, so on a long recipe the receipt would land
   somewhere down the scroll. Clipping on fire makes inset:0 mean the visible
   box again, which is what the specimen's fixed-height card implied. */
.popup.fired { overflow: hidden; }

.popup-actions { flex: 0 0 auto; }

:focus-visible {
  outline: 2px solid var(--flame);
  outline-offset: 2px;
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}
`;

writeFileSync(
  `${ext}/src/popup/popup.css`,
  [
    banner("popup", "Tokens + every .popup rule; gallery chrome dropped."),
    tokens,
    popupRules,
    popupWindow,
  ].join("\n"),
);

// ── 3. prep.css — tokens plus a form, no card ────────────────────
const prep = `${banner("Prep (options page)", "Tokens only; the form is extension-only.")}
${tokens}

* { box-sizing: border-box; }

body {
  margin: 0;
  padding: var(--space-3xl) var(--space-xl);
  background: var(--bg-page);
  color: var(--paper-primary);
  font-family: var(--font-body);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.prep {
  max-width: 560px;
  margin: 0 auto;
  background: var(--bg-card);
  color: var(--ink);
  border: 1px solid var(--rule);
}

.prep .ticket-top {
  padding: 14px 18px;
  border-bottom: 1px dashed var(--rule);
}

.prep .ticket-top .brand {
  font-family: var(--font-display);
  font-size: 10px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--ink);
}

form {
  padding: var(--space-xl) 18px var(--space-2xl);
  display: grid;
  gap: var(--space-xl);
}

.field {
  display: grid;
  gap: var(--space-sm);
  border: 0;
  margin: 0;
  padding: 0;
}

.field .label,
.field legend.label {
  font-family: var(--font-display);
  font-size: 10px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--ink-secondary);
  padding: 0;
}

.field input[type="password"],
.field select {
  font-family: var(--font-mono);
  font-size: 13px;
  padding: 10px 12px;
  color: var(--ink);
  background: var(--paper-50);
  border: 1px solid var(--rule);
  border-radius: 0;
}

.field .hint {
  font-family: var(--font-mono);
  font-size: 11px;
  line-height: 1.5;
  color: var(--ink-dim);
}

.radios {
  display: flex;
  gap: var(--space-xl);
  font-family: var(--font-mono);
  font-size: 13px;
}

.field.checkbox {
  grid-auto-flow: column;
  grid-template-columns: auto 1fr;
  justify-content: start;
  align-items: center;
  gap: var(--space-sm);
  font-family: var(--font-mono);
  font-size: 13px;
}

.actions { display: flex; align-items: center; gap: var(--space-lg); }

.actions .fire-btn {
  font-family: var(--font-display);
  font-size: 11px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  padding: 11px 20px;
  color: var(--paper-primary);
  background: var(--flame);
  border: 0;
  border-radius: 0;
  cursor: pointer;
}

.status {
  font-family: var(--font-mono);
  font-size: 11px;
  color: var(--flame);
  margin: 0;
  min-height: 1em;
}

:focus-visible {
  outline: 2px solid var(--flame);
  outline-offset: 2px;
}
`;
writeFileSync(`${ext}/src/prep/prep.css`, prep);

// ── 4. pass.css — tokens + every .popup rule (an expanded row IS the card) ──
const pass = `${banner("The Pass (full-tab history)", "Tokens + .popup rules; an expanded row IS the card.")}
${tokens}

${popupRules}

/* ─── The Pass (extension-only chrome) ────────────────────────── */

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--bg-page);
  color: var(--paper-primary);
  font-family: var(--font-body);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.pass-head {
  display: grid;
  grid-template-columns: 1fr auto auto;
  gap: var(--space-lg);
  align-items: center;
  padding: var(--space-xl) var(--space-2xl);
  border-bottom: 1px solid var(--rule-dark);
}

.pass-head h1 {
  font-family: var(--font-display);
  font-weight: 400;
  font-size: clamp(20px, 3vw, 32px);
  letter-spacing: 0.02em;
  text-transform: uppercase;
  margin: 0;
}

.pass-head input {
  font-family: var(--font-mono);
  font-size: 12px;
  padding: 8px 10px;
  min-width: 240px;
  color: var(--paper-primary);
  background: var(--bg-panel);
  border: 1px solid var(--rule-dark);
  border-radius: 0;
}

.pass-head button {
  font-family: var(--font-display);
  font-size: 10px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  padding: 9px 14px;
  color: var(--paper-primary);
  background: transparent;
  border: 1px solid var(--rule-dark);
  border-radius: 0;
  cursor: pointer;
}

.pass-head button:hover { border-color: var(--paper-muted); }

.pass-list {
  padding: var(--space-2xl);
  display: grid;
  gap: 1px;
  background: var(--rule-dark);
  max-width: 1100px;
  margin: 0 auto;
}

.pass-row {
  display: grid;
  grid-template-columns: 7ch 1fr 12ch 22ch;
  gap: var(--space-lg);
  align-items: baseline;
  padding: var(--space-md) var(--space-lg);
  background: var(--bg-page);
  font-family: var(--font-mono);
  font-size: 12px;
  cursor: pointer;
  border: 0;
  width: 100%;
  text-align: left;
  color: inherit;
}

.pass-row:hover,
.pass-row:focus-visible,
.pass-row[aria-expanded="true"] { background: var(--bg-panel); }

.pass-row .no { font-family: var(--font-display); color: var(--paper-muted); }
.pass-row .title { color: var(--paper-primary); }
.pass-row .meta {
  color: var(--paper-muted);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.pass-detail {
  background: var(--bg-page);
  padding: var(--space-xl);
  display: flex;
  justify-content: center;
}

.pass-detail .popup {
  width: 400px;
  border: 1px solid var(--rule);
  box-shadow: 0 20px 60px -20px var(--shadow);
}

.pass-empty {
  background: var(--bg-page);
  padding: var(--space-4xl);
  text-align: center;
  font-family: var(--font-display);
  font-size: 12px;
  letter-spacing: 0.08em;
  color: var(--paper-muted);
  margin: 0;
}

:focus-visible {
  outline: 2px solid var(--flame);
  outline-offset: 2px;
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}
`;
writeFileSync(`${ext}/src/pass/pass.css`, pass);

// ── 5. glyphs.ts — the pixel-art stamp marks ─────────────────────
const svgs = [...html.matchAll(/<span class="glyph-mark">(<svg[\s\S]*?<\/svg>)<\/span>/g)].map(
  (m) => m[1],
);
if (svgs.length !== 2) throw new Error(`expected 2 glyph SVGs, found ${svgs.length}`);
const [OFF_MENU, BROKEN_PLATE] = svgs;
const esc = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

mkdirSync(`${ext}/src/popup`, { recursive: true });
writeFileSync(
  `${ext}/src/popup/glyphs.ts`,
  `/**
 * Stamp glyphs — custom pixel art.
 *
 * GENERATED by extension/scripts/port-design.mjs from
 * type-specimens/popup-states.html. Do not hand-edit.
 *
 * Per CLAUDE.md the icon system is two-tier: stamp glyphs are pixel art
 * (pixellation reads at stamp size), all other chrome is Tabler outline.
 * Both use fill="currentColor" so they inherit the stamp's colour — neutral
 * ink for Off Menu, --flame-deep for Kitchen Error.
 */

/** The off-menu sheet — nothing on this page to extract. */
export const GLYPH_OFF_MENU = \`${esc(OFF_MENU)}\`;

/** The broken plate — extraction failed. Figma node 122:1728. */
export const GLYPH_BROKEN_PLATE = \`${esc(BROKEN_PLATE)}\`;
`,
);

console.log(`ported from type-specimens/popup-states.html`);
console.log(`  tokens      lines ${FONTS_START + 1}–${TOKENS_END}`);
console.log(`  popup rules lines ${POPUP_START + 1}–${POPUP_END}`);
console.log(`  glyphs      off-menu ${OFF_MENU.length}B, broken-plate ${BROKEN_PLATE.length}B`);
