/**
 * Port the locked design system out of type-specimens/ into the extension.
 *
 * The specimen is the source of truth for type, colour, and icons (locked at
 * v2.2). Nothing under src/popup/popup.css or src/popup/glyphs.ts should be
 * hand-edited — change the specimen, run a desk crit, then re-run this:
 *
 *   npm run port:design
 *
 * Extension-only chrome (the popup window box, the Archive list, the Prep
 * form) has no specimen equivalent and is authored here, clearly separated.
 * All three views ship in one stylesheet because they share one window.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ext = resolve(here, "..");
const specimens = resolve(ext, "../type-specimens");

const html = readFileSync(`${specimens}/popup-states.html`, "utf8");
const lines = html.split("\n");

// ── 1. Locate the port boundaries by content, not by hard-coded line numbers,
//       so an edit to the specimen shifts them safely.
const lineOf = (needle, from = 0) => {
  const i = lines.findIndex((l, n) => n >= from && l.includes(needle));
  if (i === -1) throw new Error(`port boundary not found: ${needle}`);
  return i;
};

const FONTS_START = lineOf("══════ Fonts ══════");
const TOKENS_END = lineOf("* { box-sizing: border-box; }", FONTS_START);
const POPUP_START = lineOf("─── Popup surface (shared)", TOKENS_END);
const POPUP_END = lineOf("─── Status legend", POPUP_START);

const dedent = (text) =>
  text
    .split("\n")
    .map((l) => (l.startsWith("      ") ? l.slice(6) : l))
    .join("\n")
    .replaceAll('url("./fonts/', 'url("../fonts/')
    .trimEnd();

/** @font-face blocks + the :root token block. Shared by all three surfaces. */
const tokens = dedent(lines.slice(FONTS_START, TOKENS_END).join("\n"));
/** Every `.popup ...` rule: card, skeleton, filmstrip, stamps, action row. */
const popupRules = dedent(lines.slice(POPUP_START, POPUP_END).join("\n"));

const banner = (surface, note) => `/* ══════════════════════════════════════════════════════════════
   Mise — ${surface}

   GENERATED by extension/scripts/port-design.mjs from
   type-specimens/popup-states.html. Do not hand-edit: change the
   specimen, run a desk crit, then \`npm run port:design\`.
   ${note}
   ══════════════════════════════════════════════════════════════ */
`;

// ── 2. popup.css ─────────────────────────────────────────────────
// Prep and Archive are panes in this window, not pages. They used to open
// tabs; Ben's note (2026-08-17) was that leaving the popup to change a
// setting or check a past recipe breaks the "fire and leave" gesture the
// product is built around. So there is one stylesheet and one window.
const popupWindow = `
/* ─── Popup window (extension-only; the specimen had no window) ── */

html,
body {
  width: 400px;
  margin: 0;
  padding: 0;
  background: var(--bg-page);
  color: var(--paper-primary);
  font-family: var(--font-body);
  /* The window surround is ink, so the scrollbar should be too. */
  color-scheme: dark;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

/* …but the card and the panes are paper, and they hold native controls — the
   Model <select> in Prep renders itself dark on a white field otherwise. */
.popup,
.surface {
  color-scheme: light;
}

body {
  /* MV3 caps popup height at 600px. The card scrolls; the actions are pinned. */
  max-height: 600px;
  display: flex;
  flex-direction: column;
}

* { box-sizing: border-box; }

/* The specimen framed each card as a gallery tile; here the card IS the
   window, so it loses its border, shadow, and fixed width. */
.popup {
  width: 100%;
  border: 0;
  box-shadow: none;
  overflow-y: auto;
  flex: 1 1 auto;
}

/* .fired-stamp is inset:0 against .popup. While .popup scrolls, that box is
   the full content height, so on a long recipe the receipt would land
   somewhere down the scroll. Clipping on fire makes inset:0 mean the visible
   box again, which is what the specimen's fixed-height card implied. */
.popup.fired { overflow: hidden; }

.popup-actions { flex: 0 0 auto; }

/* ─── View routing ───────────────────────────────────────────────
   Three surfaces share one window: the extraction card, Prep, and the
   Archive. Only one is mounted at a time. [hidden] has to win over the
   flex display below, hence !important. */
[hidden] { display: none !important; }

.surface {
  flex: 1 1 auto;
  min-height: 0;
  overflow-y: auto;
  background: var(--bg-card);
  color: var(--ink);
}

/* Every surface wears the ticket header, so switching views reads as
   turning the ticket over rather than opening a different app. */
.surface .ticket-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 14px 18px;
  border-bottom: 1px dashed var(--rule);
  position: sticky;
  top: 0;
  background: var(--bg-card);
  z-index: 1;
}

.surface .ticket-top .brand {
  font-family: var(--font-display);
  font-size: 10px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--ink);
}

:focus-visible {
  outline: 2px solid var(--flame);
  outline-offset: 2px;
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}
`;

// ── 3. Prep view — the form, scoped into the popup ───────────────
// Was a full-width options page at max-width 560px; inside a 400px popup it
// loses the centring wrapper and tightens its rhythm.
const prepView = `
/* ─── Prep (extension-only chrome) ───────────────────────────────── */

#prep-view form {
  padding: var(--space-lg) 18px var(--space-xl);
  display: grid;
  gap: var(--space-lg);
}

#prep-view .field {
  display: grid;
  gap: var(--space-sm);
  border: 0;
  margin: 0;
  padding: 0;
}

#prep-view .field .label,
#prep-view .field legend.label {
  font-family: var(--font-display);
  font-size: 10px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--ink-secondary);
  padding: 0;
}

#prep-view .field input[type="password"],
#prep-view .field select {
  font-family: var(--font-mono);
  font-size: 13px;
  padding: 9px 11px;
  width: 100%;
  color: var(--ink);
  background: var(--paper-50);
  border: 1px solid var(--rule);
  border-radius: 0;
}

#prep-view .field .hint {
  font-family: var(--font-mono);
  font-size: 11px;
  line-height: 1.45;
  color: var(--ink-dim);
}

/* The only link in the extension. Flame because it is the one action inside a
   hint, and 5.22:1 on paper carries it. */
#prep-view .field .hint a {
  color: var(--flame);
  text-underline-offset: 2px;
}

#prep-view .radios {
  display: flex;
  gap: var(--space-lg);
  font-family: var(--font-mono);
  font-size: 13px;
}

/* Form controls default to OS blue, which is the one colour the brutalist
   monochrome + flame system does not contain. Pull them onto the accent. */
#prep-view input[type="radio"],
#prep-view input[type="checkbox"] {
  accent-color: var(--flame);
}

#prep-view .field.checkbox {
  grid-auto-flow: column;
  grid-template-columns: auto 1fr;
  justify-content: start;
  align-items: center;
  gap: var(--space-sm);
  font-family: var(--font-mono);
  font-size: 12px;
  line-height: 1.4;
}

/* A checkbox field that carries a hint needs the hint under both columns
   rather than tucked beside the box. */
#prep-view .field.checkbox.explained {
  grid-auto-flow: row;
  grid-template-columns: auto 1fr;
  align-items: start;
  row-gap: 6px;
}

#prep-view .field.checkbox.explained > input {
  grid-row: 1;
  margin-top: 2px;
}

#prep-view .field.checkbox.explained > span:not(.hint) {
  grid-row: 1;
}

#prep-view .field.checkbox.explained > .hint {
  grid-column: 1 / -1;
}

#prep-view .status {
  font-family: var(--font-mono);
  font-size: 11px;
  color: var(--flame);
  margin: 0;
  padding: 0 18px var(--space-lg);
  min-height: 1em;
}
`;

// ── 4. Archive view — the list, rebuilt for 400px ────────────────
// The full-tab layout used a 7ch/1fr/12ch/22ch row and a 240px search field;
// neither survives a 400px window. Rows stack to two lines instead, and an
// expanded row still renders the real card.
const archiveView = `
/* ─── Archive (extension-only chrome) ────────────────────────────── */

#archive-view .arch-tools {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: var(--space-sm);
  padding: 10px 18px;
  border-bottom: 1px solid var(--rule);
  position: sticky;
  top: 41px;
  background: var(--bg-card);
  z-index: 1;
}

#archive-view .arch-tools input {
  font-family: var(--font-mono);
  font-size: 12px;
  padding: 7px 9px;
  width: 100%;
  color: var(--ink);
  background: var(--paper-50);
  border: 1px solid var(--rule);
  border-radius: 0;
}

#archive-view .arch-tools button {
  font-family: var(--font-display);
  font-size: 10px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  padding: 7px 11px;
  color: var(--ink-secondary);
  background: transparent;
  border: 1px solid var(--rule);
  border-radius: 0;
  cursor: pointer;
}

#archive-view .arch-tools button:hover {
  color: var(--flame);
  border-color: var(--flame);
}

#archive-view .arch-list { display: block; }

#archive-view .arch-row {
  display: grid;
  grid-template-columns: 6ch 1fr;
  column-gap: var(--space-md);
  row-gap: 2px;
  align-items: baseline;
  padding: 10px 18px;
  width: 100%;
  text-align: left;
  background: transparent;
  border: 0;
  border-bottom: 1px dashed var(--rule);
  font-family: var(--font-mono);
  font-size: 12px;
  color: var(--ink);
  cursor: pointer;
}

#archive-view .arch-row:hover,
#archive-view .arch-row[aria-expanded="true"] { background: var(--paper-50); }

#archive-view .arch-row .no {
  grid-row: span 2;
  font-family: var(--font-display);
  font-size: 11px;
  color: var(--ink-dim);
}

#archive-view .arch-row .title {
  font-family: var(--font-body);
  font-size: 13px;
  color: var(--ink);
}

#archive-view .arch-row .meta {
  grid-column: 2;
  font-size: 10px;
  color: var(--ink-dim);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* An expanded row shows the real card, so the Archive and the extraction
   screen are never two renderings of the same recipe. */
#archive-view .arch-detail {
  border-bottom: 1px solid var(--rule);
  background: var(--paper-50);
}

#archive-view .arch-detail .popup {
  width: 100%;
  border: 0;
  box-shadow: none;
  overflow: visible;
}

#archive-view .arch-empty {
  padding: var(--space-3xl) var(--space-xl);
  text-align: center;
  font-family: var(--font-display);
  font-size: 11px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--ink-dim);
  margin: 0;
}
`;

writeFileSync(
  `${ext}/src/popup/popup.css`,
  [
    banner("popup", "Tokens + every .popup rule, plus the Prep and Archive views."),
    tokens,
    popupRules,
    popupWindow,
    prepView,
    archiveView,
  ].join("\n"),
);

// ── 5. glyphs.ts — the pixel-art stamp marks ─────────────────────
const glyphs = new Map();
for (const m of html.matchAll(/<svg data-glyph="([a-z0-9-]+)"[\s\S]*?<\/svg>/g)) {
  glyphs.set(m[1], m[0]);
}
const WANTED_GLYPHS = ["off-menu", "broken-plate", "fired-flame"];
for (const want of WANTED_GLYPHS) {
  if (!glyphs.has(want)) throw new Error(`specimen is missing the ${want} stamp glyph`);
}
const OFF_MENU = glyphs.get("off-menu");
const BROKEN_PLATE = glyphs.get("broken-plate");
const FIRED_FLAME = glyphs.get("fired-flame");
const esc = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

// Tier two: the Tabler outline icons the action row wears. Lifted from the
// specimen the same way the stamp glyphs are, so the buttons in the design
// document and the buttons that ship cannot drift apart. Keyed by data-icon
// rather than by position — the row's button order changes per view.
const icons = new Map();
for (const m of html.matchAll(/<svg class="btn-icon" data-icon="([a-z0-9-]+)"[\s\S]*?<\/svg>/g)) {
  icons.set(m[1], m[0]);
}
const WANTED = ["flame", "settings", "history", "refresh", "copy", "arrow-left", "device-floppy"];
for (const want of WANTED) {
  if (!icons.has(want)) throw new Error(`specimen is missing the ${want} button icon`);
}

mkdirSync(`${ext}/src/popup`, { recursive: true });
writeFileSync(
  `${ext}/src/popup/glyphs.ts`,
  `/**
 * Stamp glyphs — custom pixel art.
 *
 * GENERATED by extension/scripts/port-design.mjs from
 * type-specimens/popup-states.html. Do not hand-edit.
 *
 * Per CLAUDE.md the icon system is two-tier: stamp glyphs are pixel art
 * (pixellation reads at stamp size), all other chrome is Tabler outline.
 * Both use fill="currentColor" so they inherit the stamp's colour — paper
 * knocked out of a filled block: --ink-dim for Off Menu, --ink-primary for
 * FIRED, --flame-deep for Kitchen Error.
 */

/** The off-menu sheet — nothing on this page to extract. */
export const GLYPH_OFF_MENU = \`${esc(OFF_MENU)}\`;

/** The broken plate — extraction failed. Figma node 122:1728. */
export const GLYPH_BROKEN_PLATE = \`${esc(BROKEN_PLATE)}\`;

/**
 * The flame — the artifact is on disk. Replaces a ✓ character: a tick is
 * app-generic, and FIRE is the verb the whole product is built around.
 * Master at type-specimens/mark/mise-fired-flame.svg.
 */
export const GLYPH_FIRED = \`${esc(FIRED_FLAME)}\`;

/**
 * Action-row icons — Tabler Icons v3.46.0, outline set, verbatim geometry.
 * Stroke is currentColor, so each one inherits its button's ink: paper on
 * the flame fill, paper-muted when Fire is disabled.
 */

/**
 * Fire — the primary action. Tabler \`flame\`, back since the 2026-10-01 desk
 * crit (it wore \`cake\` from 2026-08-31). At 1x the cake's candle merged into
 * its frosting; the flame reads at both densities and names the verb. The
 * outline flame on the button becomes the pixel flame on the FIRED stamp:
 * cause, then effect, in one symbol at two levels of finish.
 */
export const ICON_FIRE = \`${esc(icons.get("flame"))}\`;

/** Prep — settings. */
export const ICON_PREP = \`${esc(icons.get("settings"))}\`;

/** Archive — everything fired from this device, newest first. */
export const ICON_ARCHIVE = \`${esc(icons.get("history"))}\`;

/** Retry — run the failed extraction again. */
export const ICON_RETRY = \`${esc(icons.get("refresh"))}\`;

/** Copy — the finished .md to the clipboard. */
export const ICON_COPY = \`${esc(icons.get("copy"))}\`;

/** Back — out of a pane, to the extraction card. */
export const ICON_BACK = \`${esc(icons.get("arrow-left"))}\`;

/** Save — commit the Prep form. */
export const ICON_SAVE = \`${esc(icons.get("device-floppy"))}\`;
`,
);

console.log(`ported from type-specimens/popup-states.html`);
console.log(`  tokens      lines ${FONTS_START + 1}–${TOKENS_END}`);
console.log(`  popup rules lines ${POPUP_START + 1}–${POPUP_END}`);
console.log(
  `  glyphs      off-menu ${OFF_MENU.length}B, broken-plate ${BROKEN_PLATE.length}B, fired-flame ${FIRED_FLAME.length}B`,
);
